# Generated by Django 6.0.6 on 2026-07-01 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('experience', models.TextField(help_text='Describe your relevant experience')),
                ('skills', models.TextField(help_text='Comma separated skills')),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('enthusiastic', 'Enthusiastic'), ('confident', 'Confident'), ('humble', 'Humble')], default='professional', max_length=20)),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
