# Generated by Django 6.0.6 on 2026-07-01 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(max_length=200)),
                ('skills', models.TextField(help_text='Comma separated skills')),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('delivery_time', models.CharField(max_length=100)),
                ('features', models.TextField(help_text='Key features of your service')),
                ('revisions', models.IntegerField(default=1)),
                ('generated_description', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, help_text='SEO keywords for your gig', null=True)),
                ('faq_suggestions', models.TextField(blank=True, help_text='Suggested FAQs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
